// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn31pNa4QP6UH4Kxbt9L5A42eKfR3faf0',
    appId: '1:687088939951:web:7ff587c6bc42f3a66ef55a',
    messagingSenderId: '687088939951',
    projectId: 'dogwood-baton-307307',
    authDomain: 'dogwood-baton-307307.firebaseapp.com',
    storageBucket: 'dogwood-baton-307307.appspot.com',
    measurementId: 'G-G7EHGKL0B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVU9Hz2BFk2JVTMlLVKd7dzx6gj99Ufz8',
    appId: '1:687088939951:android:ff7cac4096d81ca86ef55a',
    messagingSenderId: '687088939951',
    projectId: 'dogwood-baton-307307',
    storageBucket: 'dogwood-baton-307307.appspot.com',
  );

  // Web client ID for Google Sign In (serverClientId)
  // This is the OAuth 2.0 Web client ID from Firebase Console
  // Get it from: Firebase Console > Authentication > Sign-in method > Google > Web SDK configuration
  static const String webClientId = '687088939951-hq5d0vr1po9447etls6cuh3p545m239j.apps.googleusercontent.com';

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9EPCgCnU0XiU_h2YrHVgDalDQsNwivY',
    appId: '1:687088939951:ios:87fb131995c9c0de6ef55a',
    messagingSenderId: '687088939951',
    projectId: 'dogwood-baton-307307',
    storageBucket: 'dogwood-baton-307307.appspot.com',
    androidClientId: '687088939951-346bcava9onkjalvipi53k0qboglj3j2.apps.googleusercontent.com',
    iosBundleId: 'com.byteswiz.shoppazing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9EPCgCnU0XiU_h2YrHVgDalDQsNwivY',
    appId: '1:687088939951:ios:f01d8dc782bb1f396ef55a',
    messagingSenderId: '687088939951',
    projectId: 'dogwood-baton-307307',
    storageBucket: 'dogwood-baton-307307.appspot.com',
    androidClientId: '687088939951-346bcava9onkjalvipi53k0qboglj3j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn31pNa4QP6UH4Kxbt9L5A42eKfR3faf0',
    appId: '1:687088939951:web:ace8589e7b0801c06ef55a',
    messagingSenderId: '687088939951',
    projectId: 'dogwood-baton-307307',
    authDomain: 'dogwood-baton-307307.firebaseapp.com',
    storageBucket: 'dogwood-baton-307307.appspot.com',
    measurementId: 'G-F353BLJZ9Q',
  );
}
